services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app
networks:
    app-network:
        driver: bridge
volumes:
    mysql:
        driver: local
